"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

try:
    from environs import Env
except Exception:  # pragma: no cover
    Env = None


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1q7&^zr=r8_c6__)!kxb8a#s-1a@)m$psll+cj+98ex5_t4$z4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["http://*.on-acorn.io", "https://*.on-acorn.io"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    "rest_framework",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database
# For local dev, ensure these env vars are set (or create a .env file in the project root):
#   MARIADB_DATABASE
#   MARIADB_USER
#   MARIADB_ROOT_PASSWORD
#   MARIADB_HOST (optional, default 127.0.0.1)
#   MARIADB_PORT (optional, default 3306)
#
# If environs is available, we’ll load .env automatically.
_db_env = None
if Env is not None:
    _db_env = Env()
    # .env lives at repo root (c:/practice)
    _db_env.read_env(os.path.join(BASE_DIR.parent.parent, '.env'))


def _env_str(key: str, default: str | None = None) -> str | None:
    if _db_env is not None:
        return _db_env.str(key, default=default)
    return os.getenv(key, default)


def _env_int(key: str, default: int) -> int:
    if _db_env is not None:
        return _db_env.int(key, default=default)
    return int(os.getenv(key, default))


# Local dev: use SQLite by default so `runserver` works without MySQL credentials.
_use_sqlite = True


DATABASES = (
    {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR.parent, "db.sqlite3"),
        }
    }
    if _use_sqlite
    else {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": _env_str("MARIADB_DATABASE"),
            "USER": _env_str("MARIADB_USER"),
            "PASSWORD": _env_str("MARIADB_ROOT_PASSWORD", ""),
            "HOST": _env_str("MARIADB_HOST", "127.0.0.1"),
            "PORT": _env_int("MARIADB_PORT", 3306),
        }
    }
)






# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
